all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "{{ inventory_dir }}/../../secrets/lab_admin_ed25519"
    ansible_ssh_common_args: >-
      -o UserKnownHostsFile={{ inventory_dir }}/../../.local/known_hosts
      -o StrictHostKeyChecking=yes
  children:
    controllers:
      hosts:
        controller:
          ansible_host: 192.168.130.10
    compute:
      hosts:
        compute01:
          ansible_host: 192.168.130.11
        compute02:
          ansible_host: 192.168.130.12
        compute03:
          ansible_host: 192.168.130.13
