---
- name: Refresh system CA store
  ansible.builtin.command: update-ca-certificates

- name: Restart slapd
  ansible.builtin.service:
    name: slapd
    state: restarted

- name: Restart sssd
  ansible.builtin.service:
    name: sssd
    state: restarted

- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted
